Adding validation for the required ENVs to the Run Envoy Proxy step

diff --git a/actions/setup-gap/action.yml b/actions/setup-gap/action.yml
--- a/actions/setup-gap/action.yml
+++ b/actions/setup-gap/action.yml
@@ -184,6 +184,27 @@ runs:
         K8S_API_ENDPOINT: ${{ inputs.k8s-api-endpoint }}
         PROXY_PORT: ${{ inputs.proxy-port }}
       run: |
+        # Validate required ENVs
+        required_envs=(
+          "ENABLE_PROXY_DEBUG"
+          "ENVOY_GITHUB_OIDC_TOKEN_HEDER_NAME"
+          "ENVOY_LOG_LEVEL"
+          "ENVOY_PROXY_IMAGE"
+          "GITHUB_ACTION_PATH"
+          "JWT_TOKEN"
+          "K8S_API_ENDPOINT_PORT"
+          "K8S_API_ENDPOINT"
+          "PATH_CERTS_DIR"
+          "PROXY_PORT"
+        )
+
+        for env in "${required_envs[@]}"; do
+          if [ -z "${!env}" ]; then
+            echo "Error: Environment variable $env is not set or is empty."
+            exit 1
+          fi
+        done
+
         # Get the Github OIDC hostname
         export GITHUB_OIDC_HOSTNAME=$(echo $ACTIONS_ID_TOKEN_REQUEST_URL | awk -F[/:] '{print $4}')
         if [ -z "$GITHUB_OIDC_HOSTNAME" ]; then
