More cleanup

diff --git a/actions/setup-gap/action.yml b/actions/setup-gap/action.yml
--- a/actions/setup-gap/action.yml
+++ b/actions/setup-gap/action.yml
@@ -1,13 +1,12 @@
 name: setup-gap
-description: "setup github actions proxy"
+description: "Setup GitHub Actions Proxy (GAP)"
 
 inputs:
-  # general inputs
+  # General inputs
   gap-name:
     description:
       "The name of the GAP. Used in the dir name for self-signed certs and the
-      docker container name. Required if using multiple invocations of this in
-      the same job."
+      docker container name."
     required: false
     default: "default"
   ca-cert-validity-days:
@@ -20,7 +19,8 @@ inputs:
       "The number of days the server certificate is valid for. Defaults to 1."
     required: false
     default: "1"
-  # aws role inputs
+
+  # AWS role inputs
   aws-role-duration-seconds:
     description:
       "The duration in seconds for the assumed role. Defaults to 900 (15
@@ -28,7 +28,8 @@ inputs:
     required: false
     default: "900"
   aws-region:
-    description: "The AWS region resources unless specified in other inputs"
+    description:
+      "The AWS region for resources unless specified in other inputs."
     required: false
   aws-role-arn:
     description:
@@ -36,7 +37,8 @@ inputs:
       access for private repositories, and, if for Kubernetes, EKS describe
       permissions."
     required: false
-  # k8s inputs
+
+  # Kubernetes inputs
   use-k8s:
     description:
       "Whether to setup GAP for communicating with K8s. Cannot be used with
@@ -51,26 +53,27 @@ inputs:
       "The region for the EKS cluster, if different from aws-region input."
     required: false
   k8s-api-endpoint-port:
+    description: "The port number for accessing the Kubernetes API server."
     required: false
     default: "443"
-    description: "The port number for accessing the Kubernetes API server."
-  # local proxy inputs
+
+  # Local proxy inputs
   enable-proxy-debug:
-    required: false
-    default: "false"
     description:
       "Enable or disable detailed Envoy proxy logs used for K8s API access. When
       enabled, debug logs are generated locally, and container logs are streamed
       to the console for troubleshooting."
-  github-oidc-token-header-name:
     required: false
-    default: "x-authorization-github-jwt"
+    default: "false"
+  github-oidc-token-header-name:
     description:
       "Specifies the name of the HTTP header used to pass the GitHub OIDC JWT
       token. This header is automatically injected by the local proxy and must
       not be the same as the default 'Authorization' header."
+    required: false
+    default: "x-authorization-github-jwt"
   envoy-proxy-image:
-    description: "Envoy Proxy image used to run Envoy proxy for GAP"
+    description: "Envoy Proxy image used to run Envoy proxy for GAP."
     required: false
     default: "envoyproxy/envoy:v1.33.0"
   proxy-port:
@@ -102,23 +105,45 @@ inputs:
     default: "9443"
     required: false
   websockets-services:
-    description: >
-      List of service names to be configured in the local proxy for proper
+    description:
+      "List of service names to be configured in the local proxy for proper
       handling of all required headers, including the JWT token. It should be a
-      comma-separated list, for example: "gap-ws-echo,gap-ws-hello". Note: If
+      comma-separated list, for example: 'gap-ws-echo,gap-ws-hello'. Note: If
       you are using Crib, append the Devspace namespace name as the suffix in
-      the service name, e.g., "gap-geth-${namespace-name},
-      gap-custom-ws-${namespace-name}".
+      the service name, e.g., 'gap-geth-${namespace-name},
+      gap-custom-ws-${namespace-name}'."
     default: ""
     required: false
+
 outputs:
   local-proxy-port:
     description: "The port the local proxy will listen on."
     value: ${{ inputs.proxy-port }}
+  dynamic-proxy-port:
+    description: "The port the dynamic proxy will listen on."
+    value: ${{ inputs.dynamic-proxy-port }}
+  websockets-proxy-port:
+    description: "The port the WebSocket proxy will listen on."
+    value: ${{ inputs.websockets-proxy-port }}
 
 runs:
   using: composite
   steps:
+    - name: Validate inputs
+      shell: bash
+      run: |
+        if [ -z "${{ inputs.main-dns-zone }}" ]; then
+          echo "Error: main-dns-zone is required."
+          exit 1
+        fi
+
+        if [[ "${{ inputs.dynamic-proxy-port }}" == "${{ inputs.proxy-port }}" || \
+              "${{ inputs.dynamic-proxy-port }}" == "${{ inputs.websockets-proxy-port }}" || \
+              "${{ inputs.proxy-port }}" == "${{ inputs.websockets-proxy-port }}" ]]; then
+          echo "Error: PROXY_PORT, DYNAMIC_PROXY_PORT, and WEBSOCKETS_PROXY_PORT must have unique values."
+          exit 1
+        fi
+
     - name: Assume role
       # We only need to assume a role if we intend to use k8s API server access via the proxy
       if: inputs.use-k8s == 'true'
@@ -250,17 +275,19 @@ runs:
           fi
         done
 
-        # Check if any of the listener ports have the same value
-        if [[ "$DYNAMIC_PROXY_PORT" == "$PROXY_PORT" || "$DYNAMIC_PROXY_PORT" == "$WEBSOCKETS_PROXY_PORT" || "$PROXY_PORT" == "$WEBSOCKETS_PROXY_PORT" ]]; then
-          echo "Local proxy listeners must use different values. If unsure, leave the default values and don't override PROXY_PORT, DYNAMIC_PROXY_PORT, or WEBSOCKETS_PROXY_PORT."
-          exit 1
-        fi
+        # Loop through each variable and check if it's empty
+        for var in $required_env_vars; do
+          eval value=\$$var
+          if [ -z "$value" ]; then
+            echo "Error: Required environment variable '$var' is not set."
+            exit 1
+          fi
+        done
 
         # Generate Envoy config from template
-        ls -l
         gomplate -f "${GITHUB_ACTION_PATH}/envoy.yaml.gotmpl" -o "${GITHUB_ACTION_PATH}/envoy.yaml"
 
-        # Generate LUA script from template, it can't read ENVs from filter.
+        # Generate LUA script from template
         gomplate -f "${GITHUB_ACTION_PATH}/github_oidc.lua.gotmpl" -o "${GITHUB_ACTION_PATH}/github_oidc.lua"
 
         # Copy AWS CA certs
@@ -275,18 +302,21 @@ runs:
         fi
 
         echo "Validating Envoy config..."
-        docker run --rm \
-          --name "gap-v2" \
-          -p "${DYNAMIC_PROXY_PORT}:${DYNAMIC_PROXY_PORT}" \
-          -p "${PROXY_PORT}:${PROXY_PORT}" \
-          -p "${WEBSOCKETS_PROXY_PORT}:${WEBSOCKETS_PROXY_PORT}" \
-          -v "${PATH_CERTS_DIR}":/tls \
-          -v "${GITHUB_ACTION_PATH}/envoy.yaml":/etc/envoy/envoy.yaml \
-          -v "${GITHUB_ACTION_PATH}/json.lua":/etc/envoy/json.lua \
-          -v "${GITHUB_ACTION_PATH}/github_oidc.lua":/etc/envoy/github_oidc.lua \
-          "${ENVOY_PROXY_IMAGE}" \
-          /usr/local/bin/envoy --mode validate -c /etc/envoy/envoy.yaml \
-          --log-level "${PROXY_LOG_LEVEL}"
+        if ! docker run --rm \
+            --name "gap-v2" \
+            -p "${DYNAMIC_PROXY_PORT}:${DYNAMIC_PROXY_PORT}" \
+            -p "${PROXY_PORT}:${PROXY_PORT}" \
+            -p "${WEBSOCKETS_PROXY_PORT}:${WEBSOCKETS_PROXY_PORT}" \
+            -v "${PATH_CERTS_DIR}":/tls \
+            -v "${GITHUB_ACTION_PATH}/envoy.yaml":/etc/envoy/envoy.yaml \
+            -v "${GITHUB_ACTION_PATH}/json.lua":/etc/envoy/json.lua \
+            -v "${GITHUB_ACTION_PATH}/github_oidc.lua":/etc/envoy/github_oidc.lua \
+            "${ENVOY_PROXY_IMAGE}" \
+            /usr/local/bin/envoy --mode validate -c /etc/envoy/envoy.yaml \
+            --log-level "${PROXY_LOG_LEVEL}"; then
+          echo "Error: Envoy configuration validation failed."
+          exit 1
+        fi
 
         echo "Starting the local Envoy proxy..."
         docker run --rm -d \
