additional features and improved error logging for llm-pr-writer 0.2.0 (#219)
* minor adjustments + add exclude paths to pr writer

* change depth to pr number to fix default value error

* handle append file

* read prompt from file

* allow invocation by chatops

* improve API error handling

* update readme

* add changeset

* update readme

* wraps env usage in brackets

diff --git a/actions/llm-pr-writer/action.yml b/actions/llm-pr-writer/action.yml
--- a/actions/llm-pr-writer/action.yml
+++ b/actions/llm-pr-writer/action.yml
@@ -1,12 +1,4 @@
 name: llm-pr-writer
-description:
-  "This GitHub workflow harnesses the capabilities of Large Language Models
-  (LLMs) to automate the creation and enhancement of pull request (PR)
-  descriptions. Designed to streamline the development process, it significantly
-  reduces the time and effort traditionally required to draft comprehensive PR
-  descriptions, particularly for extensive changes. By meticulously analyzing
-  the modifications within a PR, the workflow generates precise, context-rich
-  summaries that facilitate improved collaboration and review efficiency."
 
 inputs:
   # general inputs
@@ -27,9 +19,20 @@ inputs:
     description: "openai api key"
     required: true
   openai-model:
-    description: "openai model"
+    description: "openai model. defaults to 'gpt-3.5-turbo-0125'. use 'gpt-4-0125-preview' if your codebase is complex or large."
     required: false
-    default: "gpt-4-0125-preview"
+    default: "gpt-3.5-turbo-0125"
+  exclude-paths:
+    description: "semi-colon(;) separated paths to exclude from diff"
+    required: false
+    type: string
+  pr-append-file:
+    description: "path to a markdown or text file to append to the PR message (checklist, etc.)"
+    required: false
+  workflow-ref:
+    description: "ref of the workflow to checkout"
+    required: false
+    default: "main"
   # grafana inputs
   metrics-job-name:
     description: "grafana metrics job name"
@@ -48,54 +51,119 @@ inputs:
 runs:
   using: composite
   steps:
-    - name: Checkout repo
+    - name: Check if the event is a pull request or comment body starts with `/gpt-create-pr`
+      shell: bash
+      if: >
+       github.event_name == 'pull_request' ||
+       (github.event.issue.pull_request && startsWith(github.event.comment.body, '/gpt-create-pr'))
+      run: |
+        echo "SKIP_ACTION=false" >> $GITHUB_ENV
+
+    - name: Checkout calling repo
+      if: ${{ env.SKIP_ACTION == 'false' }}
       uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
       with:
         fetch-depth: ${{ inputs.checkout-repo-fetch-depth }}
 
+    - name: Checkout action repo
+      if: ${{ env.SKIP_ACTION == 'false' }}
+      uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
+      with:
+        repository: smartcontractkit/.github
+        ref: ${{ inputs.workflow-ref }}
+        path: 'pr_writer_actions'
+        # prevents access to any other action and workflow files
+        sparse-checkout: |
+          actions/llm-pr-writer/pr-writer-prompt.md
+        sparse-checkout-cone-mode: false
+        fetch-depth: 1
+
+    - name: Format diff exclude filter
+      if: ${{ env.SKIP_ACTION == 'false' }}
+      shell: bash
+      id: filter
+      run: |
+        IFS=';' read -ra exclude_paths_arr <<< "${{ inputs.exclude-paths }}"
+        for i in "${!exclude_paths_arr[@]}"; do
+          exclude_paths_arr[$i]="':!${exclude_paths_arr[$i]}'"
+        done
+
+        echo "exclude_filter="${exclude_paths_arr[@]}"" >> "$GITHUB_OUTPUT"
+
+    # Fail early to avoid unnecessary API calls
+    - name: If pr-append-file is set, check if it exists
+      if: ${{ env.SKIP_ACTION == 'false' && inputs.pr-append-file }}
+      shell: bash
+      id: check_pr-append-file
+      run: |
+        if [ ! -f ${{ inputs.pr-append-file }} ]; then
+          echo "::error::pr-append-file was set but does not exist"
+          exit 1
+        else
+          echo "result=exists" >> "$GITHUB_OUTPUT"
+        fi
+
     - name: Get diff output
-      # TODO: create a script to include exclusion of paths and/or files
+      if: ${{ env.SKIP_ACTION == 'false' }}
       shell: bash
       env:
         GH_TOKEN: ${{ inputs.gh-token }}
-        BRANCH: ${{ inputs.checkout-repo-fetch-depth }}
+        PR_NUMBER: ${{ github.event.issue.number || github.event.pull_request.number || '' }}
       run: |
-        diff_output=$(gh pr diff "$BRANCH")
+        gh pr checkout $PR_NUMBER
+        diff_command="git diff origin/\$(gh pr view --json baseRefName | jq -r '.baseRefName')...HEAD -- ${{ steps.filter.outputs.exclude_filter }}"
+        diff_output=$(eval $diff_command)
+        
         # escape all special characters and prepare for json with jq
         echo "$diff_output" | jq -Rs . | sed 's/^"//;s/"$//' > diff_output.txt
 
     - name: Call ChatGPT
+      if: ${{ env.SKIP_ACTION == 'false' }}
       shell: bash
       run: |
         diff_output=$(cat diff_output.txt)
+        openai_prompt=$(cat pr_writer_actions/actions/llm-pr-writer/pr-writer-prompt.md)
         openai_model=${{ inputs.openai-model }}
-        prompt_response=$(echo '{
+        openai_result=$(echo '{
           "model": "'$openai_model'",
           "temperature": 0.7,
           "messages": [
             {
               "role": "system",
-              "content": "You are a helpful expert data engineer with expertise in Blockchain and Decentralized Oracle Networks. Given the patch output of `git diff` command in the triple backticks at the bottom of the reply, your task is to help create a pull request message in order to facilitate and encourage reviews from your peers by focusing on the 2 primary topic: Why and What\n\n**What**\nA bullet point summary what has been changed. Objective and straight to the point. Organize and list the changes made to a specific file, focusing on the specifics of the changes, ie: what file, what change, and a brief sentence on the effect of the change (if any). For each file, group related changes as subitems under the same list item, indented with double spacebar characters and no linebreaks between list items.\n\n**Why**\nBased on the changes summarized in **What**, go through item by item of the list you wrote to understand the changes, then write a short paragraph (within 500 characters) summarizing the changes and their purposes without implying any assumptions about the broader context.\n\nAfter having done all that, output your response starting from **Why** and then **What** in escaped, raw markdown text that can be sent as http body to API (do not wrap in code block).\n\nPreamble your answer with a bold \"Below is a summarization created by an LLM\".\n Format \"why\" and \"what\" as Heading 2 using double sharp characters (##).\nOtherwise, do not include any another preamble and postamble to your answer. If there is no code within the triple backticks, kindly reply that there is no code to generate the pull-request message. \n  ```'$diff_output'``` \n"
+              "content": "'$openai_prompt' \n\n```'$diff_output'```\n"
             }
           ]
         }' | envsubst | curl https://api.openai.com/v1/chat/completions \
+                      -w "%{http_code}" \
+                      -o prompt_response.json \
                       -H "Content-Type: application/json" \
                       -H "Authorization: Bearer ${{ inputs.openai-api-key }}" \
                       -d @-
         )
 
+        # throw error openai_result when is not 200
+        if [ "$openai_result" != '200' ]; then
+          echo "::error::OpenAI API call failed with status $openai_result: $(cat prompt_response.json)"
+          exit 1
+        fi
+
         # replace lines starting with ' -' (1space) with '  -' (2spaces)
-        response_content=$(echo "$prompt_response" | jq -r '.choices[0].message.content')
+        response_content=$(cat prompt_response.json | jq -r '.choices[0].message.content')
         echo "$response_content" | sed -e 's/^ -/  -/g' > chatgpt_output.txt
 
+    - name: Append additional content to output
+      if: ${{ env.SKIP_ACTION == 'false' && steps.check_pr-append-file.outputs.result == 'exists' }}
+      shell: bash
+      run: |
+        echo "Appending content to PR"
+        cat ${{ inputs.pr-append-file }} >> chatgpt_output.txt
+
     - name: Generate PR summary
+      if: ${{ env.SKIP_ACTION == 'false' }}
       shell: bash
       env:
         GH_TOKEN: ${{ inputs.gh-token }}
-        BRANCH: ${{ inputs.checkout-repo-fetch-depth }}
-        PR_NUMBER:
-          ${{ github.event.issue.number || github.event.pull_request.number ||
-          '' }}
+        PR_NUMBER: ${{ github.event.issue.number || github.event.pull_request.number || '' }}
       run: |
         # get the current body of the PR
         pr_current_body="$(gh pr view $PR_NUMBER --json body | jq -r '.body')"
@@ -105,17 +173,11 @@ runs:
         pr_current_body=$(echo "$pr_current_body" | sed -e '/<!-- DON'\''T DELETE. add your comments above llm generated contents -->/,$d')
         echo "$pr_current_body"
 
-        pr_message=$(cat chatgpt_output.txt)
+        pr_message="**Below is a summarization created by an LLM (${{ inputs.openai-model }}). Be mindful of hallucinations and verify accuracy.**
+        
+        $(cat chatgpt_output.txt)"
 
-        # if .github/pull_request_append.md exists, append to pr_message after a linebreak
-        if [ -f .github/pull_request_append.md ]; then
-          pr_message="$pr_message
-
-        $(cat .github/pull_request_append.md)
-        "
-        fi
-
-        gh pr edit $BRANCH -b "$pr_current_body
+        gh pr edit $PR_NUMBER -b "$pr_current_body
         <!-- DON'T DELETE. add your comments above llm generated contents -->
         ---
         $pr_message
