handle append file

diff --git a/actions/llm-pr-writer/action.yml b/actions/llm-pr-writer/action.yml
--- a/actions/llm-pr-writer/action.yml
+++ b/actions/llm-pr-writer/action.yml
@@ -34,8 +34,8 @@ inputs:
     description: "semi-colon(;) separated paths to exclude from diff"
     required: false
     type: string
-  append_markdown:
-    description: "markdown filename with extension to append to the PR message (checklist, etc.)"
+  pr_append_file:
+    description: "path to a markdown or text file to append to the PR message (checklist, etc.)"
     required: false
   # grafana inputs
   metrics-job-name:
@@ -71,6 +71,18 @@ runs:
 
         echo "exclude_filter="${exclude_paths_arr[@]}"" >> "$GITHUB_OUTPUT"
 
+    # Fail early to avoid unnecessary API calls
+    - name: If pr_append_file is set, check if it exists
+      shell: bash
+      id: check_pr_append_file
+      if: ${{ inputs.pr_append_file }}
+      run: |
+        if [ ! -f ${{ inputs.pr_append_file }} ]; then
+          echo "pr_append_file was set but does not exist"
+          exit 1
+        fi
+        echo "result=exists" >> "$GITHUB_OUTPUT"
+
     - name: Get diff output
       shell: bash
       env:
@@ -103,15 +115,23 @@ runs:
                       -H "Authorization: Bearer ${{ inputs.openai-api-key }}" \
                       -d @-
         )
-        # # throw error if response is empty or 'null'
-        # if [ -z "$prompt_response" ] || [ "$prompt_response" == "null" ]; then
-        #   echo "ChatGPT response is empty or null"
-        #   exit 1
-        # fi
+
+        # throw error if response is empty or 'null'
+        if [ -z "$prompt_response" ] || [ "$prompt_response" == "null" ]; then
+          echo "ChatGPT response is empty or null"
+          exit 1
+        fi
 
         # replace lines starting with ' -' (1space) with '  -' (2spaces)
         response_content=$(echo "$prompt_response" | jq -r '.choices[0].message.content')
         echo "$response_content" | sed -e 's/^ -/  -/g' > chatgpt_output.txt
+
+    - name: Append additional content to output
+      if: ${{ steps.check_pr_append_file.outputs.result == 'exists' }}
+      shell: bash
+      run: |
+        echo "Appending content to PR"
+        cat ${{ inputs.pr_append_file }} >> chatgpt_output.txt
 
     - name: Generate PR summary
       shell: bash
@@ -127,17 +147,9 @@ runs:
         pr_current_body=$(echo "$pr_current_body" | sed -e '/<!-- DON'\''T DELETE. add your comments above llm generated contents -->/,$d')
         echo "$pr_current_body"
 
-        pr_message="**Below is a summarization created by an LLM ($inputs.openai-model). Model hallucinations could result in mistakes.**
+        pr_message="**Below is a summarization created by an LLM ({{ $inputs.openai-model }}). Be mindful of hallucinations and verify accuracy.**
         
         $(cat chatgpt_output.txt)"
-
-        # if append_markdown input exists, append to pr_message after a linebreak
-        if [ -f .github/${{ inputs.append_markdown }} ]; then
-          pr_message="$pr_message
-
-        $(cat .github/${{ inputs.append_markdown }})
-        "
-        fi
 
         gh pr edit $PR_NUMBER -b "$pr_current_body
         <!-- DON'T DELETE. add your comments above llm generated contents -->
