Support optional inputs when not pushing to ECR

diff --git a/actions/build-push-docker/action.yml b/actions/build-push-docker/action.yml
--- a/actions/build-push-docker/action.yml
+++ b/actions/build-push-docker/action.yml
@@ -53,17 +53,21 @@ inputs:
     required: false
     default: "true"
   docker-registry-url:
-    required: true
+    required: false
     description: |
       Hostname for the docker image registry.
+
+      Required when inputs.docker-push is true.
 
       Examples:
         public.ecr.aws
         <account-id>.dkr.ecr.<region>.amazonaws.com
   docker-repository-name:
-    required: true
+    required: false
     description: |
       Name of the Docker repository excluding hostname. Excludes any tags. Public ECR's will include a registry alias and a forward slash.
+
+      Required when inputs.docker-push is true.
 
       Examples:
         chainlink/chainlink # Public ECR
@@ -103,11 +107,17 @@ inputs:
     required: false
     default: "us-east-1"
   aws-account-number:
-    description: "AWS account number for the ECR registry."
-    required: true
+    description: |
+      AWS account number for the ECR registry.
+
+      Required when inputs.docker-push is true.
+    required: false
   aws-role-arn:
-    description: "AWS role ARN with permissions to push ECR images."
-    required: true
+    description: |
+      AWS role ARN with permissions to push ECR images.
+
+      Required when inputs.docker-push is true.
+    required: false
 
 outputs:
   docker-repository-name:
@@ -126,6 +136,35 @@ outputs:
 runs:
   using: composite
   steps:
+    - name: Validate input combinations
+      shell: bash
+      env:
+        DOCKER_PUSH: ${{ inputs.docker-push }}
+        DOCKER_REGISTRY_URL: ${{ inputs.docker-registry-url }}
+        DOCKER_REPOSITORY_NAME: ${{ inputs.docker-repository-name }}
+      run: |
+        if [[ "${DOCKER_PUSH}" == true ]]; then
+          if [[ -z "${AWS_ACCOUNT_NUMBER}" ]]; then
+            echo "::error::aws-account-number input is required when docker-push is true."
+            exit 1
+          fi
+
+          if [[ -z "${AWS_ROLE_ARN}" ]]; then
+            echo "::error::aws-role-arn input is required when docker-push is true."
+            exit 1
+          fi
+
+          if [[ -z "${DOCKER_REGISTRY_URL}" ]]; then
+            echo "::error::docker-registry-url input is required when docker-push is true."
+            exit 1
+          fi
+
+          if [[ -z "${DOCKER_REPOSITORY_NAME}" ]]; then
+            echo "::error::docker-repository-name input is required when docker-push is true."
+            exit 1
+          fi
+        fi
+
     - name: Check runner arch and platform compatibility
       shell: bash
       env:
