fix: branch-out-upload behaviour

diff --git a/actions/branch-out-upload/action.yml b/actions/branch-out-upload/action.yml
--- a/actions/branch-out-upload/action.yml
+++ b/actions/branch-out-upload/action.yml
@@ -81,13 +81,19 @@ runs:
         variant: ${{ inputs.trunk-variant }}
 
     - name: Check junit-enhancer outcomes
-      if: ${{ steps.run-junit-enhancer.outcome == 'failure' }}
       shell: bash
+      if: ${{ always() }}
       env:
         TRUNK_UPLOAD_ONLY: ${{ inputs.trunk-upload-only }}
+        STEP_RESULT: ${{ steps.run-junit-enhancer.outcome }}
       run: |
-        echo "The JUnit Enhancer step failed. This is typically due to it detecting build failures in the test reports."
-        if [[ "${TRUNK_UPLOAD_ONLY}" == "false" ]]; then
-          echo "::error::Failing the workflow as auto-quarantine is enabled, and junit-enhancer reported failures."
-          exit 1
+        echo "Found junit-enhancer step result: ${STEP_RESULT}, and TRUNK_UPLOAD_ONLY is set to: ${TRUNK_UPLOAD_ONLY}"
+
+        if [[ "${STEP_RESULT}" == "failure" ]]; then
+          echo "::error::The JUnit Enhancer step failed. This is typically due to it detecting build failures in the test reports."
+
+          if [[ "${TRUNK_UPLOAD_ONLY}" == "false" ]]; then
+            echo "::error::Failing the workflow as auto-quarantine is enabled, and junit-enhancer reported failures."
+            exit 1
+          fi
         fi
