chore: bump build-push-docker (#1077)
* chore: bump build-push-docker

* fix: get trunk via GH CLI

* fix: add quotes

diff --git a/.github/workflows/reusable-docker-build-publish.yml b/.github/workflows/reusable-docker-build-publish.yml
--- a/.github/workflows/reusable-docker-build-publish.yml
+++ b/.github/workflows/reusable-docker-build-publish.yml
@@ -94,13 +94,15 @@ on:
         description: "Docker build arguments."
         required: false
         type: string
-      docker-build-cache-disabled:
+      docker-cache-behaviour:
         description: |
-          Disable Docker build cache. See `--no-cache` flag in:
-          https://docs.docker.com/engine/reference/commandline/buildx_build/#cache
+          Controls how the docker build cache is used.
+          - "disable" completely disables the cache.
+          - "enable" enables the cache, reading from and writing to it on every event.
+          - "write-on-trunk" enables the cache, but only writes to it on pushes to the default branch. (default)
         required: false
         type: string
-        default: "false"
+        default: "write-on-trunk"
       docker-build-context:
         description: "Path to Docker build context."
         required: true
@@ -233,6 +235,9 @@ jobs:
       git-short-sha: ${{ steps.git-short-sha.outputs.short-sha }}
       pr-number: ${{ steps.set-extra-outputs.outputs.pr-number }}
       build-type: ${{ steps.set-extra-outputs.outputs.build-type }}
+      docker-restore-cache:
+        ${{ steps.should-cache.outputs.docker-restore-cache }}
+      docker-save-cache: ${{ steps.should-cache.outputs.docker-save-cache }}
     steps:
       - uses: actions/checkout@v4
         with:
@@ -285,6 +290,46 @@ jobs:
             echo "build-type=manual" | tee -a "$GITHUB_OUTPUT"
           else
             echo "::error::Unsupported GitHub event name: ${GITHUB_EVENT_NAME}"
+            exit 1
+          fi
+
+      - name: Get repo trunk branch
+        id: get-trunk
+        if: ${{ inputs.docker-cache-behaviour == 'write-on-trunk' }}
+        env:
+          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+          GITHUB_WORKFLOW_REPOSITORY: ${{ inputs.github-workflow-repository }}
+        run: |
+          trunk=$(gh repo view "${GITHUB_WORKFLOW_REPOSITORY}" --json defaultBranchRef --jq .defaultBranchRef.name)
+          if [[ -z "${trunk}" ]]; then
+            echo "::warn::Failed to get trunk branch using gh cli. Defaulting to 'main'."
+            trunk="main"
+          fi
+          echo "trunk=${trunk}" | tee -a "${GITHUB_OUTPUT}"
+
+      - name: Check docker cache constraints
+        id: should-cache
+        env:
+          GITHUB_REF_NAME: ${{ inputs.github-ref-name }}
+          GITHUB_EVENT_NAME: ${{ inputs.github-event-name }}
+          REPO_TRUNK: ${{ steps.get-trunk.outputs.trunk }}
+          DOCKER_CACHE_BEHAVIOUR: ${{ inputs.docker-cache-behaviour }}
+        run: |
+          if [[ "${DOCKER_CACHE_BEHAVIOUR}" == "disable" ]]; then
+            echo "docker-restore-cache=false" | tee -a "${GITHUB_OUTPUT}"
+            echo "docker-save-cache=false" | tee -a "${GITHUB_OUTPUT}"
+          elif [[ "${DOCKER_CACHE_BEHAVIOUR}" == "enable" ]]; then
+            echo "docker-restore-cache=true" | tee -a "${GITHUB_OUTPUT}"
+            echo "docker-save-cache=true" | tee -a "${GITHUB_OUTPUT}"
+          elif [[ "${DOCKER_CACHE_BEHAVIOUR}" == "write-on-trunk" ]]; then
+              echo "docker-restore-cache=true" | tee -a "${GITHUB_OUTPUT}"
+            if [[ "${GITHUB_REF_NAME}" == "${REPO_TRUNK}" ]] && [[ "${GITHUB_EVENT_NAME}" == "push" ]]; then
+              echo "docker-save-cache=true" | tee -a "${GITHUB_OUTPUT}"
+            else
+              echo "docker-save-cache=false" | tee -a "${GITHUB_OUTPUT}"
+            fi
+          else
+            echo "::error::Invalid DOCKER_CACHE_BEHAVIOUR: ${DOCKER_CACHE_BEHAVIOUR}. Must be one of: disabled, enabled, write-on-trunk."
             exit 1
           fi
 
@@ -385,7 +430,7 @@ jobs:
             exit 1
           fi
           # Append the arch (example: "-arm64") to the tag value.
-          tags="type=raw,value=${tag_value}-${MATRIX_ARCH}"                
+          tags="type=raw,value=${tag_value}-${MATRIX_ARCH}"
           echo "tags=${tags}" | tee -a "${GITHUB_OUTPUT}"
           # This will be used to generate the docker manifest tag in a future
           # job (without the arch suffix).
@@ -415,7 +460,7 @@ jobs:
 
       - name: Docker image build
         id: build
-        uses: smartcontractkit/.github/actions/build-push-docker@build-push-docker/0.6.1
+        uses: smartcontractkit/.github/actions/build-push-docker@build-push-docker/0.7.0
         with:
           platform: ${{ format('linux/{0}', matrix.arch) }}
           docker-registry-url: >-
@@ -432,7 +477,8 @@ jobs:
           tags: ${{ steps.set-docker-image-tags.outputs.tags }}
           dockerfile: ${{ inputs.dockerfile }}
           docker-build-args: ${{ inputs.docker-build-args }}
-          docker-build-cache-disabled: ${{ inputs.docker-build-cache-disabled }}
+          docker-restore-cache: ${{ needs.init.outputs.docker-restore-cache }}
+          docker-save-cache: ${{ needs.init.outputs.docker-save-cache }}
           context: ${{ inputs.docker-build-context }}
           aws-account-number: ${{ secrets.AWS_ACCOUNT_ID }}
           aws-role-arn: ${{ secrets.AWS_ROLE_PUBLISH_ARN }}
